import { createContext, useContext, useState, useEffect } from 'react';

const ThemeContext = createContext();

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error('useTheme must be used within a ThemeProvider');
  }
  return context;
};

export const translations = {
  en: {
    welcome: 'Welcome',
    dashboard: 'Dashboard',
    home: 'Home',
    entry: 'Entry',
    sandbox: 'Sandbox',
    learn: 'Learn',
    legacy: 'Legacy',
    analytics: 'Analytics',
    notifications: 'Notifications',
    settings: 'Settings',
    logout: 'Logout',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    clearData: 'Clear Data',
    save: 'Save',
    cancel: 'Cancel',
    back: 'Back',
    netWorth: 'Net Worth',
    assets: 'Assets',
    liabilities: 'Liabilities',
    recentTransactions: 'Recent Transactions',
    viewAll: 'View All',
    healthScore: 'Health Score',
    financialOverview: 'Financial Overview',
    budgetAlert: 'Budget Alert',
    modify: 'Modify',
    addItem: 'Add Item',
    description: 'Description',
    amount: 'Amount',
    category: 'Category',
    addTransaction: 'Add Transaction',
    features: 'Features',
    howItWorks: 'How it Works',
    security: 'Security',
    signIn: 'Sign In',
    getStarted: 'Get Started',
    startFree: 'Start For Free',
    viewDemo: 'View Demo',
    heroTitle: 'Master Your Financial Legacy',
    heroSub: 'The all-in-one platform for family finance. Track expenses, forecast your future, and secure your assets for the next generation.',
    profileSettings: 'Profile Settings',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    customerCategory: 'Customer Category',
    saveProfile: 'Save Profile',
    changesSaved: 'Changes saved!',
    enterName: 'Enter your name',
    enterEmail: 'Enter your email',
    enterPhone: 'Enter your phone',
    selectCategory: 'Select category',
    individual: 'Individual',
    business: 'Business',
    premium: 'Premium',
    student: 'Student',
    spendingAnalysis: 'Spending Analysis',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    monOverMon: 'Month-on-Month',
    prevMonth: 'Previous Month',
    nextMonth: 'Next Month',
    aiInsights: 'AI Insights',
    smartTips: 'Smart Tips',
    noTransactions: 'No transactions found for this month.',
    managePreferences: 'Manage your preferences',
    appearance: 'Appearance',
    dataManagement: 'Data Management',
    confirmClear: 'Are you sure you want to clear all data? This cannot be undone.',
    healthExcellent: 'Excellent! Your finances are in great shape.',
    healthVeryGood: 'Very Good! Your savings ratio is strong.',
    healthGood: 'Good! Keep monitoring your debt.',
    healthNeedsAttention: 'Needs attention. Focus on reducing debt.',
    budgetSpentPrefix: "You've used",
    budgetSpentSuffix: 'of your monthly budget',
    fromLastMonth: 'from last month',
    healthScoreExplanation: 'Your score is based on savings ratio, debt management, and insurance coverage.',
    analyticsSub: 'AI-Powered Financial Insights',
    vsLastMonth: 'vs last month',
    noDataCompare: 'No data to compare',
    expenseBreakdown: 'Expense Breakdown',
    smartTip: 'Smart Tip',
    tipShopping: "Your spending spike this month is driven by Shopping. Try the Sandbox to plan next month's purchases.",
    tipSaving: "You're consistently saving! Check the 'Invest' tab to grow this month's surplus.",
    transactionsIn: 'Transactions in',
    entriesLabel: 'entries',
    howItWorks: 'How it Works',
    security: 'Security',
    signIn: 'Sign In',
    getStarted: 'Get Started',
    liveBeta: 'Live Beta Available',
    masterYour: 'Master Your',
    financialLegacy: 'Financial Legacy',
    heroDesc: 'The all-in-one platform for family finance. Track expenses, forecast your future, and secure your assets for the next generation.',
    startForFree: 'Start For Free',
    viewDemo: 'View Demo',
    bankGradeSecurity: 'Bank-Grade Security',
    aesEncryption: 'AES-256 Encryption',
    aesDesc: 'Your data is encrypted at rest and in transit.',
    zeroKnowledge: 'Zero Knowledge',
    zeroDesc: 'We cannot see your personal financial details.',
    biometricReady: 'Biometric Ready',
    biometricDesc: 'Compatible with device-level authentication.',
    rightsReserved: 'All rights reserved.',
    voiceNotepad: 'Smart Voice Notepad',
    voiceDesc: "Logging expenses shouldn't be a chore. Just speak, and our AI categorizes everything instantly.",
    nlpAccurate: 'Natural Language Processing for accurate categorization',
    instantScan: 'Instant receipt scanning and data extraction',
    multiCurrency: 'Multi-currency support with real-time conversion',
    recurringDetection: 'Automatic recurring expense detection',
    expenditureSandbox: 'Expenditure Sandbox',
    sandboxDesc: 'Simulate major purchases. See how buying a new car or home affects your long-term wealth before you spend a dime.',
    monteCarlo: 'Monte Carlo simulations for wealth projection',
    impactAnalysis: 'Impact analysis of big-ticket items',
    stressTest: 'Stress test your portfolio against market crashes',
    visualTimeline: 'Visual timeline of asset growth vs. liabilities',
    nomineeVault: 'Nominee Vault',
    nomineeDesc: 'Ensure your family is protected. Securely store insurance policies, crypto keys, and legal documents for emergency access.',
    deadManSwitch: "Dead man's switch protocol for data release",
    multiSig: 'Multi-sig access for beneficiaries',
    encryptedStorage: 'Encrypted document storage with zero-knowledge proof',
    automatedCheckins: 'Automated check-ins to verify your status',
    learnMoreAbout: 'Learn more about',
    smartEntrySub: 'Quickly add transactions manually or use AI tools.',
    descPlaceholder: 'What was this for?',
    fastTrack: 'Fast Track',
    voiceEntry: 'Voice Entry',
    voiceExample: '"Spent 500 on dinner"',
    tapToRecord: 'Tap to Record',
    listening: 'Listening...',
    stop: 'Stop',
    processing: 'Processing...',
    parsed: 'Parsed',
    confirm: 'Confirm',
    retry: 'Retry',
    scanReceipt: 'Scan Receipt',
    uploadPlaceholder: 'Drop file or click to upload',
    uploadLimits: 'PDF, JPG, PNG (Max 5MB)',
    expense: 'Expense',
    income: 'Income',
    Food: 'Food',
    Transport: 'Transport',
    Utilities: 'Utilities',
    Entertainment: 'Entertainment',
    Shopping: 'Shopping',
    Health: 'Health',
    Education: 'Education',
    Other: 'Other',
    backToWebsite: 'Back to website',
    totalNetWorth: 'Total Net Worth',
    capturingWealth: 'Capturing Wealth,',
    securingLegacies: 'Securing Legacies.',
    authDesc: 'The most advanced platform for tracking, simulation, and estate planning.',
    welcomeBack: 'Welcome back',
    noAccount: "Don't have an account?",
    signUp: 'Sign up',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    signingIn: 'Signing in...',
    signInBtn: 'Sign In',
    orLoginWith: 'Or log in with',
    createAccount: 'Create an account',
    alreadyHaveAccount: 'Already have an account?',
    loginBtn: 'Log in',
    firstName: 'First name',
    lastName: 'Last name',
    agreeTerms: 'I agree to the Terms & Conditions',
    creatingAccount: 'Creating account...',
    createAccountBtn: 'Create account',
    orRegisterWith: 'Or register with',
    sandboxSub: 'Simulate purchases and investments',
    blueprintMode: 'Blueprint Mode',
    normalMode: 'Normal Mode',
    blueprintActive: 'Blueprint Mode Active',
    simulationsOnly: 'All calculations are simulations - no actual changes',
    purchaseSimulator: 'Purchase Simulator',
    purchaseAmount: 'Purchase Amount',
    impactAnalysisTitle: 'Impact Analysis',
    afterPurchase: 'After Purchase:',
    change: 'Change:',
    purchaseImpactDesc: 'represents',
    ofNetWorth: 'of net worth',
    simulatePurchaseBtn: 'Simulate Purchase',
    investmentCalculator: 'Investment Calculator',
    monthlyInvestmentLabel: 'Monthly Investment',
    investmentPeriod: 'Investment Period',
    expectedROI: 'Expected Annual Return',
    projectionResults: 'Projection Results',
    totalInvested: 'Total Invested:',
    projectedValue: 'Projected Value:',
    gains: 'Gains:',
    quickScenarios: 'Quick What-If Scenarios',
    highImpact: 'High Impact',
    lowImpact: 'Low Impact',
    learnSub: 'Improve your financial knowledge with bite-sized lessons',
    financeSnackTitle: 'Finance Snack of the Day',
    microLessons: 'Micro-Lessons',
    markAsComplete: 'Mark as Complete',
    featuredArticles: 'Featured Articles',
    viewAllArticles: 'View All Articles',
    notStarted: 'Not started',
    completed: 'Completed',
    legacySub: 'Secure your financial future for your loved ones',
    recommendedProtection: 'Recommended Protection',
    nominees: 'Nominees',
    saveNominee: 'Save Nominee',
    noNominees: 'No nominees added yet',
    addNomineesToSecure: 'Add nominees to secure your assets',
    secureVault: 'Secure Document Vault',
    highSecurityArea: 'High Security Area',
    vaultAuthDesc: 'This vault contains sensitive documents. Requires re-authentication.',
    pinPlaceholder: 'Enter 4-digit PIN',
    unlockVault: 'Unlock Vault',
    vaultUnlocked: 'Vault Unlocked',
    lockVault: 'Lock Vault',
    nomineeAccessSummary: 'Nominee Access Summary',
    emergencyInfo: 'Emergency Information',
    emergencyDesc: 'In case of emergency, your nominees can access this vault by verifying their identity. Make sure to inform your nominees about this feature and how to access it.',
  },
  te: {
    welcome: 'స్వాగతం',
    dashboard: 'డ్యాష్‌బోర్డ్',
    home: 'హోమ్',
    entry: 'ఎంట్రీ',
    sandbox: 'శాండ్‌బాక్స్',
    learn: 'నేర్చుకోండి',
    legacy: 'లెగసీ',
    analytics: 'విశ్లేషణలు',
    notifications: 'నోటిఫికేషన్లు',
    settings: 'సెట్టింగ్‌లు',
    logout: 'లాగ్ అవుట్',
    theme: 'థీమ్',
    darkMode: 'డార్క్ మోడ్',
    lightMode: 'లైట్ మోడ్',
    language: 'భాష',
    clearData: 'డేటాను క్లియర్ చేయండి',
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు చేయండి',
    back: 'వెనుకకు',
    netWorth: 'నికర విలువ',
    assets: 'ఆస్తులు',
    liabilities: 'అప్పులు',
    recentTransactions: 'ఇటీవలి లావాదేవీలు',
    viewAll: 'అన్నీ చూడండి',
    healthScore: 'ఆరోగ్య సూచిక',
    financialOverview: 'ఆర్థిక అవలోకనం',
    budgetAlert: 'బడ్జెట్ హెచ్చరిక',
    modify: 'సవరించండి',
    addItem: 'అంశాన్ని జోడించండి',
    description: 'వివరణ',
    amount: 'మొత్తం',
    category: 'వర్గం',
    addTransaction: 'లావాదేవీని జోడించండి',
    features: 'లక్షణాలు',
    howItWorks: 'ఇది ఎలా పనిచేస్తుంది',
    security: 'భద్రత',
    signIn: 'సైన్ ఇన్',
    getStarted: 'ప్రారంభించండి',
    startFree: 'ఉచితంగా ప్రారంభించండి',
    viewDemo: 'డెమో చూడండి',
    heroTitle: 'మీ ఆర్థిక వారసత్వ నిర్వహణ',
    heroSub: 'కుటుంబ ఆర్థికం కోసం ఆల్ ఇన్ వన్ ప్లాట్‌ఫారమ్. ఖర్చులను ట్రాక్ చేయండి మరియు మీ ఆస్తులను రక్షించుకోండి.',
    profileSettings: 'ప్రొఫైల్ సెట్టింగ్‌లు',
    fullName: 'పూర్తి పేరు',
    emailAddress: 'ఈమెయిల్ చిరునామా',
    phoneNumber: 'ఫోన్ నంబర్',
    customerCategory: 'కస్టమర్ వర్గం',
    saveProfile: 'ప్రొఫైల్ సేవ్ చేయి',
    changesSaved: 'మార్పులు సేవ్ చేయబడ్డాయి!',
    individual: 'వ్యక్తిగత',
    business: 'వ్యాపార',
    premium: 'ప్రీమియం',
    student: 'విద్యార్థి',
    spendingAnalysis: 'ఖర్చు విశ్లేషణ',
    totalIncome: 'మొత్తం ఆదాయం',
    totalExpenses: 'మొత్తం ఖర్చులు',
    monOverMon: 'నెలవారీ పోలిక',
    prevMonth: 'మునుపటి నెల',
    nextMonth: 'తదుపరి నెల',
    aiInsights: 'AI అంతర్దృష్టులు',
    smartTips: 'స్మార్ట్ చిట్కాలు',
    noTransactions: 'ఈ నెలలో లావాదేవీలు ఏవీ లేవు.',
    managePreferences: 'మీ ప్రాధాన్యతలను నిర్వహించండి',
    appearance: 'రూపం',
    dataManagement: 'డేటా నిర్వహణ',
    confirmClear: 'మీరు మొత్తం డేటాను క్లియర్ చేయాలనుకుంటున్నారా? ఇది తిరిగి పొందలేము.',
    healthExcellent: 'అద్భుతం! మీ ఆర్థిక పరిస్థితి చాలా బాగుంది.',
    healthVeryGood: 'చాలా మంచిది! మీ పొదుపు నిష్పత్తి బలంగా ఉంది.',
    healthGood: 'మంచిది! మీ అప్పులను పర్యవేక్షిస్తూ ఉండండి.',
    healthNeedsAttention: 'శ్రద్ధ అవసరం. అప్పులను తగ్గించుకోవడంపై దృష్టి పెట్టండి.',
    budgetSpentPrefix: 'మీరు మీ నెలవారీ బడ్జెట్‌లో',
    budgetSpentSuffix: 'ఉపయోగించారు',
    fromLastMonth: 'గత నెల నుండి',
    healthScoreExplanation: 'మీ స్కోర్ పొదుపు నిష్పత్తి, అప్పుల నిర్వహణ మరియు బీమా కవరేజీపై ఆధారపడి ఉంటుంది.',
    analyticsSub: 'AI-ఆధారిత ఆర్థిక అంతర్దృష్టులు',
    vsLastMonth: 'గత నెలతో పోలిస్తే',
    noDataCompare: 'పోల్చడానికి డేటా లేదు',
    expenseBreakdown: 'ఖర్చుల విశ్లేషణ',
    smartTip: 'స్మార్ట్ చిట్కా',
    tipShopping: 'ఈ నెలలో మీ ఖర్చులు షాపింగ్ వల్ల పెరిగాయి. వచ్చే నెల ప్లాన్ చేయడానికి శాండ్‌బాక్స్‌ని ప్రయత్నించండి.',
    tipSaving: 'మీరు స్థిరంగా పొదుపు చేస్తున్నారు! ఈ నెల మిగులును పెంచడానికి ఇన్వెస్ట్ ట్యాబ్‌ని చూడండి.',
    transactionsIn: 'లో లావాదేవీలు',
    entriesLabel: 'నమోదులు',
    howItWorks: 'ఇది ఎలా పనిచేస్తుంది',
    security: 'భద్రత',
    signIn: 'సైన్ ఇన్',
    getStarted: 'ప్రారంభించండి',
    liveBeta: 'లైవ్ బీటా అందుబాటులో ఉంది',
    masterYour: 'మీరు సాధించండి',
    financialLegacy: 'ఆర్థిక వారసత్వం',
    heroDesc: 'కుటుంబ ఆర్థిక వ్యవహారాల కోసం ఆల్ ఇన్ వన్ ప్లాట్‌ఫారమ్. ఖర్చులను ట్రాక్ చేయండి, మీ భవిష్యత్తును అంచనా వేయండి మరియు తదుపరి తరం కోసం మీ ఆస్తులను భద్రపరచుకోండి.',
    startForFree: 'ఉచితంగా ప్రారంభించండి',
    viewDemo: 'డెమో చూడండి',
    bankGradeSecurity: 'బ్యాంక్-స్థాయి భద్రత',
    aesEncryption: 'AES-256 ఎన్‌క్రిప్షన్',
    aesDesc: 'మీ డేటా విశ్రాంతి సమయంలో మరియు రవాణా సమయంలో ఎన్‌క్రిప్ట్ చేయబడుతుంది.',
    zeroKnowledge: 'జీరో నాలెడ్జ్',
    zeroDesc: 'మేము మీ వ్యక్తిగత ఆర్థిక వివరాలను చూడలేము.',
    biometricReady: 'బయోమెట్రిక్ సిద్ధంగా ఉంది',
    biometricDesc: 'డివైస్-స్థాయి ప్రామాణీకరణతో అనుకూలంగా ఉంటుంది.',
    rightsReserved: 'అన్ని హక్కులు ప్రత్యేకించబడ్డాయి.',
    voiceNotepad: 'స్మార్ట్ వాయిస్ నోట్‌ప్యాడ్',
    voiceDesc: 'ఖర్చులను నమోదు చేయడం ఇకపై శ్రమతో కూడుకున్న పని కాదు. కేవలం మాట్లాడండి, మా AI ప్రతిదీ తక్షణమే వర్గీకరిస్తుంది.',
    nlpAccurate: 'ఖచ్చితమైన వర్గీకరణ కోసం నేచురల్ లాంగ్వేజ్ ప్రాసెసింగ్',
    instantScan: 'తక్షణ రసీదు స్కానింగ్ మరియు డేటా సంగ్రహణ',
    multiCurrency: 'నిజ-సమయ మార్పిడితో బహుళ-కరెన్సీ మద్దతు',
    recurringDetection: 'ఆటోమేటిక్ రికరింగ్ ఖర్చుల గుర్తింపు',
    expenditureSandbox: 'ఖర్చుల శాండ్‌బాక్స్',
    sandboxDesc: 'పెద్ద కొనుగోళ్లను అనుకరించండి. కొత్త కారు లేదా ఇల్లు కొనడం వల్ల మీ దీర్ఘకాలిక సంపద ఎలా ప్రభావితమవుతుందో తెలుసుకోండి.',
    monteCarlo: 'సంపద అంచనా కోసం మోంటే కార్లో అనుకరణలు',
    impactAnalysis: 'పెద్ద వస్తువుల ప్రభావ విశ్లేషణ',
    stressTest: 'మార్కెట్ క్రాష్‌లకు వ్యతిరేకంగా మీ పోర్ట్‌ఫోలియోను పరీక్షించండి',
    visualTimeline: 'ఆస్తుల వృద్ధి వర్సెస్ అప్పుల దృశ్య కాలక్రమం',
    nomineeVault: 'నామినీ వాల్ట్',
    nomineeDesc: 'మీ కుటుంబం సురక్షితంగా ఉందని నిర్ధారించుకోండి. అత్యవసర యాక్సెస్ కోసం బీమా పాలసీలు, క్రిప్టో కీలు మరియు చట్టపరమైన పత్రాలను సురక్షితంగా భద్రపరుచుకోండి.',
    deadManSwitch: 'డేటా విడుదల కోసం డెడ్ మాన్ స్విచ్ ప్రోటోకాల్',
    multiSig: 'లబ్ధిదారుల కోసం మల్టీ-సిగ్ యాక్సెస్',
    encryptedStorage: 'జీరో-నాలెడ్జ్ ప్రూఫ్ తో ఎన్‌క్రిప్టెడ్ డాక్యుమెంట్ స్టోరేజ్',
    automatedCheckins: 'మీ స్థితిని ధృవీకరించడానికి స్వయంచాలక చెక్-ఇన్‌లు',
    learnMoreAbout: 'గురించి మరింత తెలుసుకోండి',
    smartEntrySub: 'లావాదేవీలను మాన్యువల్‌గా జోడించండి లేదా AI సాధనాలను ఉపయోగించండి.',
    descPlaceholder: 'ఇది దేని కోసం?',
    fastTrack: 'ఫాస్ట్ ట్రాక్',
    voiceEntry: 'వాయిస్ ఎంట్రీ',
    voiceExample: '"డిన్నర్ కోసం 500 ఖర్చు చేశాను"',
    tapToRecord: 'రికార్డ్ చేయడానికి నొక్కండి',
    listening: 'వింటున్నారు...',
    stop: 'ఆపండి',
    processing: 'ప్రాసెస్ చేస్తున్నారు...',
    parsed: 'విశ్లేషించబడింది',
    confirm: 'ధృవీకరించండి',
    retry: 'మళ్లీ ప్రయత్నించండి',
    scanReceipt: 'రసీదును స్కాన్ చేయండి',
    uploadPlaceholder: 'ఫైల్‌ను ఇక్కడ వదలండి లేదా అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి',
    uploadLimits: 'PDF, JPG, PNG (గరిష్టంగా 5MB)',
    expense: 'ఖర్చు',
    income: 'ఆదాయం',
    Food: 'ఆహారం',
    Transport: 'రవాణా',
    Utilities: 'వినియోగాలు',
    Entertainment: 'వినోదం',
    Shopping: 'షాపింగ్',
    Health: 'ఆరోగ్యం',
    Education: 'విద్య',
    Other: 'ఇతర',
    backToWebsite: 'వెబ్‌సైట్‌కి తిరిగి వెళ్లండి',
    totalNetWorth: 'మొత్తం నికర విలువ',
    capturingWealth: 'సంపదను పట్టుకోవడం,',
    securingLegacies: 'వారసత్వాలను భద్రపరచడం.',
    authDesc: 'ట్రాకింగ్, సిమ్యులేషన్ మరియు ఎస్టేట్ ప్లానింగ్ కోసం అత్యంత అధునాతన ప్లాట్‌ఫారమ్.',
    welcomeBack: 'మళ్ళీ స్వాగతం',
    noAccount: 'ఖాతా లేదా?',
    signUp: 'సైన్ అప్',
    emailPlaceholder: 'ఈమెయిల్',
    passwordPlaceholder: 'మీ పాస్‌వర్డ్ నమోదు చేయండి',
    rememberMe: 'నన్ను గుర్తుంచుకో',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    signingIn: 'సైన్ ఇన్ అవుతోంది...',
    signInBtn: 'సైన్ ఇన్',
    orLoginWith: 'లేదా వీటితో లాగిన్ అవ్వండి',
    createAccount: 'ఖాతాను సృష్టించండి',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    loginBtn: 'లాగిన్',
    firstName: 'మొదటి పేరు',
    lastName: 'చివరి పేరు',
    agreeTerms: 'నేను నిబంధనలు మరియు షరతులకు అంగీకరిస్తున్నాను',
    creatingAccount: 'ఖాతా సృష్టించబడుతోంది...',
    createAccountBtn: 'ఖాతాను సృష్టించండి',
    orRegisterWith: 'లేదా వీటితో నమోదు చేసుకోండి',
    sandboxSub: 'కొనుగోళ్లు మరియు పెట్టుబడులను అనుకరించండి',
    blueprintMode: 'బ్లూప్రింట్ మోడ్',
    normalMode: 'సాధారణ మోడ్',
    blueprintActive: 'బ్లూప్రింట్ మోడ్ యాక్టివ్‌గా ఉంది',
    simulationsOnly: 'అన్ని లెక్కలు అనుకరణలు మాత్రమే - వాస్తవ మార్పులు ఉండవు',
    purchaseSimulator: 'కొనుగోలు సిమ్యులేటర్',
    purchaseAmount: 'కొనుగోలు మొత్తం',
    impactAnalysisTitle: 'ప్రభావ విశ్లేషణ',
    afterPurchase: 'కొనుగోలు తర్వాత:',
    change: 'మార్పు:',
    purchaseImpactDesc: 'సూచిస్తుంది',
    ofNetWorth: 'నికర విలువలో',
    simulatePurchaseBtn: 'కొనుగోలును అనుకరించండి',
    investmentCalculator: 'పెట్టుబడి కాలిక్యులేటర్',
    monthlyInvestmentLabel: 'నెలవారీ పెట్టుబడి',
    investmentPeriod: 'పెట్టుబడి కాలం',
    expectedROI: 'ఆశించిన వార్షిక రాబడి',
    projectionResults: 'అంచనా ఫలితాలు',
    totalInvested: 'మొత్తం పెట్టుబడి:',
    projectedValue: 'అంచనా వేసిన విలువ:',
    gains: 'లాభాలు:',
    quickScenarios: 'త్వరిత క్విక్ సినారియోలు',
    highImpact: 'ఎక్కువ ప్రభావం',
    lowImpact: 'తక్కువ ప్రభావం',
    learnSub: 'చిన్న పాఠాలతో మీ ఆర్థిక పరిజ్ఞానాన్ని మెరుగుపరచుకోండి',
    financeSnackTitle: 'నేటి ఆర్థిక చిట్కా',
    microLessons: 'సూక్ష్మ పాఠాలు',
    markAsComplete: 'పూర్తయినట్లు గుర్తు పెట్టండి',
    featuredArticles: 'ప్రముఖ వ్యాసాలు',
    viewAllArticles: 'అన్ని వ్యాసాలను చూడండి',
    notStarted: 'ప్రారంభించలేదు',
    completed: 'పూర్తయింది',
    legacySub: 'మీ ప్రియమైన వారి కోసం మీ ఆర్థిక భవిష్యత్తును భద్రపరచుకోండి',
    recommendedProtection: 'సిఫార్సు చేయబడిన రక్షణ',
    nominees: 'నామినీలు',
    saveNominee: 'నామినీని సేవ్ చేయండి',
    noNominees: 'ఇంకా నామినీలు జోడించబడలేదు',
    addNomineesToSecure: 'మీ ఆస్తులను భద్రపరచడానికి నామినీలను జోడించండి',
    secureVault: 'సురక్షిత డాక్యుమెంట్ వాల్ట్',
    highSecurityArea: 'అధిక భద్రతా ప్రాంతం',
    vaultAuthDesc: 'ఈ వాల్ట్‌లో సున్నితమైన పత్రాలు ఉన్నాయి. మళ్లీ ప్రామాణీకరణ అవసరం.',
    pinPlaceholder: '4-అంకెల PIN ని నమోదు చేయండి',
    unlockVault: 'వాల్ట్‌ని అన్‌లాక్ చేయండి',
    vaultUnlocked: 'వాల్ట్ అన్‌లాక్ చేయబడింది',
    lockVault: 'వాల్ట్‌ని లాక్ చేయండి',
    nomineeAccessSummary: 'నామినీ యాక్సెస్ సారాంశం',
    emergencyInfo: 'అత్యవసర సమాచారం',
    emergencyDesc: 'అత్యవసర పరిస్థితుల్లో, మీ నామినీలు వారి గుర్తింపును ధృవీకరించడం ద్వారా ఈ వాల్ట్‌ని యాక్సెస్ చేయవచ్చు. ఈ ఫీచర్ మరియు దాన్ని ఎలా యాక్సెస్ చేయాలో మీ నామినీలకు తెలియజేయండి.',
  },
  hi: {
    welcome: 'स्वागत है',
    dashboard: 'डैशबोर्ड',
    home: 'होम',
    entry: 'प्रविष्टि',
    sandbox: 'सैंडबॉक्स',
    learn: 'सीखें',
    legacy: 'लेगेसी',
    analytics: 'एनालिटिक्स',
    notifications: 'सूचनाएं',
    settings: 'सेटिंग्स',
    logout: 'लॉग आउट',
    theme: 'थीम',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    language: 'भाषा',
    clearData: 'डेटा साफ़ करें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    back: 'वापस',
    netWorth: 'कुल मूल्य',
    assets: 'संपत्ति',
    liabilities: 'देयताएं',
    recentTransactions: 'हाल के लेनदेन',
    viewAll: 'सभी देखें',
    healthScore: 'स्वास्थ्य स्कोर',
    financialOverview: 'वित्तीय अवलोकन',
    budgetAlert: 'बजट चेतावनी',
    modify: 'संशोधित करें',
    addItem: 'आइटम जोड़ें',
    description: 'विवरण',
    amount: 'राशि',
    category: 'श्रेणी',
    addTransaction: 'लेनदेन जोड़ें',
    features: 'विशेषताएं',
    howItWorks: 'यह कैसे काम करता है',
    security: 'सुरक्षा',
    signIn: 'साइन इन',
    getStarted: 'शुरू करें',
    startFree: 'मुफ्त में शुरू करें',
    viewDemo: 'डेमो देखें',
    heroTitle: 'अपनी वित्तीय विरासत में महारत हासिल करें',
    heroSub: 'पारिवारिक वित्त के लिए ऑल-इन-वन प्लेटफॉर्म। खर्चों को ट्रैक करें और अपनी संपत्ति को सुरक्षित करें।',
    profileSettings: 'प्रोफ़ाइल सेटिंग्स',
    fullName: 'पूरा नाम',
    emailAddress: 'ईमेल पता',
    phoneNumber: 'फ़ोन नंबर',
    customerCategory: 'ग्राहक श्रेणी',
    saveProfile: 'प्रोफ़ाइल सहेजें',
    changesSaved: 'परिवर्तन सहेजे गए!',
    individual: 'व्यक्तिगत',
    business: 'व्यापार',
    premium: 'प्रीमियम',
    student: 'छात्र',
    spendingAnalysis: 'व्यय विश्लेषण',
    totalIncome: 'कुल आय',
    totalExpenses: 'कुल व्यय',
    monOverMon: 'माह-दर-माह',
    prevMonth: 'पिछला महीना',
    nextMonth: 'अगला महीना',
    aiInsights: 'AI अंतर्दृष्टि',
    smartTips: 'स्मार्ट टिप्स',
    noTransactions: 'इस महीने के लिए कोई लेनदेन नहीं मिला।',
    managePreferences: 'अपनी प्राथमिकताएं प्रबंधित करें',
    appearance: 'दिखावट',
    dataManagement: 'डेटा प्रबंधन',
    confirmClear: 'क्या आप वाकई सारा डेटा साफ़ करना चाहते हैं? इसे वापस नहीं लिया जा सकता।',
    healthExcellent: 'उत्कृष्ट! आपकी आर्थिक स्थिति बहुत अच्छी है।',
    healthVeryGood: 'बहुत अच्छा! आपका बचत अनुपात मजबूत है।',
    healthGood: 'अच्छा! अपने कर्ज की निगरानी करते रहें।',
    healthNeedsAttention: 'ध्यान देने की जरूरत है। कर्ज कम करने पर ध्यान दें।',
    budgetSpentPrefix: 'आपने अपने मासिक बजट का',
    budgetSpentSuffix: 'उपयोग किया है',
    fromLastMonth: 'पिछले महीने से',
    healthScoreExplanation: 'आपका स्कोर बचत अनुपात, ऋण प्रबंधन और बीमा कवरेज पर आधारित है।',
    analyticsSub: 'AI-संचालित वित्तीय अंतर्दृष्टि',
    vsLastMonth: 'पिछले महीने की तुलना में',
    noDataCompare: 'तुलना करने के लिए कोई डेटा नहीं',
    expenseBreakdown: 'व्यय विश्लेषण',
    smartTip: 'स्मार्ट टिप',
    tipShopping: 'इस महीने आपके खर्चों में बढ़ोतरी शॉपिंग के कारण हुई है। अगले महीने की योजना बनाने के लिए सैंडबॉक्स का उपयोग करें।',
    tipSaving: 'आप लगातार बचत कर रहे हैं! इस महीने के सरप्लस को बढ़ाने के लिए "इन्वेस्ट" टैब देखें।',
    transactionsIn: 'में लेनदेन',
    entriesLabel: 'प्रविष्टियाँ',
    howItWorks: 'यह कैसे काम करता है',
    security: 'सुरक्षा',
    signIn: 'साइन इन करें',
    getStarted: 'शुरू करें',
    liveBeta: 'लाइव बीटा उपलब्ध है',
    masterYour: 'माहिर बनें',
    financialLegacy: 'वित्तीय विरासत में',
    heroDesc: 'पारिवारिक वित्त के लिए ऑल-इन-वन प्लेटफॉर्म। खर्चों को ट्रैक करें, अपने भविष्य का पूर्वानुमान लगाएं और अगली पीढ़ी के लिए अपनी संपत्ति सुरक्षित करें।',
    startForFree: 'मुफ्त में शुरू करें',
    viewDemo: 'डेमो देखें',
    bankGradeSecurity: 'बैंक-स्तरीय सुरक्षा',
    aesEncryption: 'AES-256 एन्क्रिप्शन',
    aesDesc: 'आपका डेटा सुरक्षित रूप से एन्क्रिप्ट किया गया है।',
    zeroKnowledge: 'शून्य ज्ञान',
    zeroDesc: 'हम आपके व्यक्तिगत वित्तीय विवरण नहीं देख सकते।',
    biometricReady: 'बायोमेट्रिक तैयार',
    biometricDesc: 'डिवाइस-स्तरीय प्रमाणीकरण के साथ संगत।',
    rightsReserved: 'सर्वाधिकार सुरक्षित।',
    voiceNotepad: 'स्मार्ट वॉयस नोटपैड',
    voiceDesc: 'खर्चों को दर्ज करना अब कठिन काम नहीं होना चाहिए। बस बोलें, और हमारा AI सब कुछ तुरंत वर्गीकृत कर देगा।',
    nlpAccurate: 'सटीक वर्गीकरण के लिए नेचुरल लैंग्वेज प्रोसेसिंग',
    instantScan: 'त्वरित रसीद स्कैनिंग और डेटा निकालना',
    multiCurrency: 'वास्तविक समय रूपांतरण के साथ मल्टी-करेंसी सपोर्ट',
    recurringDetection: 'स्वचालित आवर्ती व्यय पहचान',
    expenditureSandbox: 'व्यय सैंडबॉक्स',
    sandboxDesc: 'बड़ी खरीदारी का अनुकरण करें। देखें कि नई कार या घर खरीदने से आपके दीर्घकालिक धन पर क्या प्रभाव पड़ता है।',
    monteCarlo: 'धन प्रक्षेपण के लिए मोंटे कार्लो सिमुलेशन',
    impactAnalysis: 'बड़ी वस्तुओं का प्रभाव विश्लेषण',
    stressTest: 'बाजार क्रैश के खिलाफ अपने पोर्टफोलियो का परीक्षण करें',
    visualTimeline: 'संपत्ति वृद्धि बनाम देनदारियों की दृश्य समयरेखा',
    nomineeVault: 'नॉमिनी वॉल्ट',
    nomineeDesc: 'सुनिश्चित करें कि आपका परिवार सुरक्षित है। आपातकालीन पहुंच के लिए बीमा पॉलिसियों, क्रिप्टो कुंजियों और कानूनी दस्तावेजों को सुरक्षित रूप से संग्रहीत करें।',
    deadManSwitch: 'डेटा रिलीज के लिए डेड मैन स्विच प्रोटोकॉल',
    multiSig: 'लाभार्थियों के लिए मल्टी-सिग एक्सेस',
    encryptedStorage: 'जीरो-नॉलेज प्रूफ के साथ एन्क्रिप्टेड दस्तावेज़ भंडारण',
    automatedCheckins: 'आपकी स्थिति सत्यापित करने के लिए स्वचालित चेक-इन',
    learnMoreAbout: 'के बारे में और जानें',
    smartEntrySub: 'लेनदेन को मैन्युअल रूप से जोड़ें या AI टूल का उपयोग करें।',
    descPlaceholder: 'यह किसके लिए था?',
    fastTrack: 'फास्ट ट्रैक',
    voiceEntry: 'वॉयस एंट्री',
    voiceExample: '"रात के खाने पर 500 खर्च किए"',
    tapToRecord: 'रिकॉर्ड करने के लिए टैप करें',
    listening: 'सुन रहे हैं...',
    stop: 'रुकें',
    processing: 'प्रसंस्करण...',
    parsed: 'विश्लेषण किया गया',
    confirm: 'पुष्टि करें',
    retry: 'पुनः प्रयास करें',
    scanReceipt: 'रसीद स्कैन करें',
    uploadPlaceholder: 'फ़ाइल छोड़ें या अपलोड करने के लिए क्लिक करें',
    uploadLimits: 'PDF, JPG, PNG (अधिकतम 5MB)',
    expense: 'खर्च',
    income: 'आय',
    Food: 'भोजन',
    Transport: 'परिवहन',
    Utilities: 'उपयोगिताएँ',
    Entertainment: 'मनोरंजन',
    Shopping: 'खरीदारी',
    Health: 'स्वास्थ्य',
    Education: 'शिक्षा',
    Other: 'अन्य',
    backToWebsite: 'वेबसाइट पर वापस जाएं',
    totalNetWorth: 'कुल निवल मूल्य',
    capturingWealth: 'धन को संजोना,',
    securingLegacies: 'विरासत को सुरक्षित करना।',
    authDesc: 'ट्रैकिंग, सिमुलेशन और एस्टेट प्लानिंग के लिए सबसे उन्नत प्लेटफॉर्म।',
    welcomeBack: 'वापसी पर स्वागत है',
    noAccount: 'खाता नहीं है?',
    signUp: 'साइन अप करें',
    emailPlaceholder: 'ईमेल',
    passwordPlaceholder: 'अपना पासवर्ड दर्ज करें',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    signingIn: 'साइन इन हो रहा है...',
    signInBtn: 'साइन इन',
    orLoginWith: 'या इसके साथ लॉग इन करें',
    createAccount: 'खाता बनाएं',
    alreadyHaveAccount: 'पहले से ही खाता है?',
    loginBtn: 'लॉग इन',
    firstName: 'पहला नाम',
    lastName: 'अंतिम नाम',
    agreeTerms: 'मैं नियमों और शर्तों से सहमत हूँ',
    creatingAccount: 'खाता बनाया जा रहा है...',
    createAccountBtn: 'खाता बनाएं',
    orRegisterWith: 'या इसके साथ रजिस्टर करें',
    sandboxSub: 'खरीदारी और निवेश का अनुकरण करें',
    blueprintMode: 'ब्लूप्रिंट मोड',
    normalMode: 'सामान्य मोड',
    blueprintActive: 'ब्लूप्रिंट मोड सक्रिय है',
    simulationsOnly: 'सभी गणनाएं अनुकरण हैं - कोई वास्तविक परिवर्तन नहीं',
    purchaseSimulator: 'खरीद सिम्युलेटर',
    purchaseAmount: 'खरीद राशि',
    impactAnalysisTitle: 'प्रभाव विश्लेषण',
    afterPurchase: 'खरीद के बाद:',
    change: 'परिवर्तन:',
    purchaseImpactDesc: 'दर्शाता है',
    ofNetWorth: 'कुल संपत्ति का',
    simulatePurchaseBtn: 'खरीद का अनुकरण करें',
    investmentCalculator: 'निवेश कैलकुलेटर',
    monthlyInvestmentLabel: 'मासिक निवेश',
    investmentPeriod: 'निवेश अवधि',
    expectedROI: 'अपेक्षित वार्षिक रिटर्न',
    projectionResults: 'प्रक्षेपण परिणाम',
    totalInvested: 'कुल निवेश किया गया:',
    projectedValue: 'अनुमानित मूल्य:',
    gains: 'लाभ:',
    quickScenarios: 'त्वरित परिदृश्य',
    highImpact: 'उच्च प्रभाव',
    lowImpact: 'कम प्रभाव',
    learnSub: 'छोटे पाठों के साथ अपने वित्तीय ज्ञान में सुधार करें',
    financeSnackTitle: 'आज का वित्तीय नुस्खा',
    microLessons: 'सूक्ष्म पाठ',
    markAsComplete: 'पूर्ण के रूप में चिह्नित करें',
    featuredArticles: 'विशेष लेख',
    viewAllArticles: 'सभी लेख देखें',
    notStarted: 'शुरू नहीं हुआ',
    completed: 'पूरा हुआ',
    legacySub: 'अपने प्रियजनों के लिए अपना वित्तीय भविष्य सुरक्षित करें',
    recommendedProtection: 'अनुशंसित सुरक्षा',
    nominees: 'नामांकित व्यक्ति',
    saveNominee: 'नामांकित व्यक्ति सहेजें',
    noNominees: 'अभी तक कोई नामांकित व्यक्ति नहीं जोड़ा गया',
    addNomineesToSecure: 'अपनी संपत्ति सुरक्षित करने के लिए नामांकित व्यक्ति जोड़ें',
    secureVault: 'सुरक्षित दस्तावेज़ तिजोरी',
    highSecurityArea: 'उच्च सुरक्षा क्षेत्र',
    vaultAuthDesc: 'इस तिजोरी में संवेदनशील दस्तावेज़ हैं। पुन: प्रमाणीकरण की आवश्यकता है।',
    pinPlaceholder: '4-अंकीय पिन दर्ज करें',
    unlockVault: 'तिजोरी अनलॉक करें',
    vaultUnlocked: 'तिजोरी अनलॉक हो गई',
    lockVault: 'तिजोरी लॉक करें',
    nomineeAccessSummary: 'नामांकित व्यक्ति पहुंच सारांश',
    emergencyInfo: 'आपातकालीन जानकारी',
    emergencyDesc: 'आपात स्थिति में, आपके नामांकित व्यक्ति अपनी पहचान सत्यापित करके इस तिजोरी तक पहुँच सकते हैं। सुनिश्चित करें कि आप अपने नामांकित व्यक्तियों को इस सुविधा और इस तक पहुँचने के तरीके के बारे में सूचित करें।',
  },
};

export const ThemeProvider = ({ children }) => {
  // Enforce Light Mode
  const theme = 'light';

  // Language State
  const [language, setLanguage] = useState(() => {
    const savedLang = localStorage.getItem('language');
    return savedLang || 'en';
  });

  // Apply Theme Side Effect (Force light mode)
  useEffect(() => {
    const root = window.document.documentElement;
    root.classList.remove('dark');
    root.classList.add('light');
    localStorage.setItem('theme', 'light');
  }, []);

  // Save Language Side Effect
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleTheme = () => {
    // No-op: Theme is locked to light
    console.log("Theme is locked to light mode.");
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  const value = {
    theme,
    toggleTheme,
    language,
    setLanguage,
    t,
  };

  return <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>;
};
